### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by TheW0NK** [steveiliop56/PyOS#2]
# Professional Operating System Developer
I recently attempted to use your program but encountered several challenges.

An operating system without a bootloader or kernel is more accurately described as a user interface layer. These layers are increasingly rare, often deprecated, and typically come with higher expectations, such as:

- Compatibility with the three main operating systems: Windows, Linux, and macOS.
- A fully functional graphical user interface (GUI).
- An independent windowing system.
- No reliance on external software or interpreters from third-party websites (e.g., IDLE).

Ultimately, your "OS" cannot be classified as a legitimate operating system or a user interface layer. The inability to run on widely used platforms, particularly Windows, may explain its limited adoption. Additionally, the lack of a user interface or bootable file further diminishes its standing compared to established systems.

Throughout my career, I have developed numerous Python-based user interface layers and gradually transitioned into full operating systems, which typically involve the use of five primary languages: Assembly, C, Docker, JSON, and Makefile.

I am not suggesting that you abandon this repository, but I strongly encourage you to consider ways to enhance it. If you're open to advice, I recommend focusing on compiling this project into a standalone .exe file that operates without external dependencies.

**Comment by steveiliop56** [comment]
Hello @TheW0NK,

My project is clearly not an os, it is mostly a joke. I made this when I was learning python just so I can learn the language better. It's not in any terms an os but I it tries to emulate a Unix like shell. Hope that covers you.

**Comment by TheW0NK** [comment]
I can take things too seriously 😂
